name: Spacelift Stacks

on:
  pull_request:
    branches:
      - main

jobs:
  manage-stacks:
    runs-on: ubuntu-latest
    name: Manage Stacks

    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: spacelift-io/setup-spacectl@v1.0.0

      - uses: tj-actions/changed-files@v43
        id: changed-files
        with:
          files: |
            **/terraform.tf

      - run: |
          spacectl stack list
          spacectl profile current

#      - run: |
#          spacectl profile login omicron7
#          jwt=$(spacectl profile export-token)
#          echo "JWT=$jwt" >> "$GITHUB_OUTPUT"
#        id: spacelift
#
#      - run: |
#          for file in ${ADDED_FILES}; do
#            echo "$file was added"
#            name=$(dirname $file)
#          done
#
#          curl --request POST \
#            --url $SPACELIFT_API_KEY_ENDPOINT/graphql \
#            --header 'Authorization: Bearer $SPACELIFT_JWT' \
#            --header 'Content-Type: application/json' \
#            --data '{"query":"{ stacks { id name, administrative, createdAt, description }}"}'
#        env:
#          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
#          SPACELIFT_JWT: ${{ steps.spacelift.outputs.JWT }}
